// Centralisation des codes d'erreurs liés aux scans & présence
// Facilite le merge avec d'autres branches et l'évolution future.

export const SCAN_QR_ERROR_CODES = {
  APPT_QR_INVALID: 'APPT_QR_INVALID',
  APPT_NOT_FOUND: 'APPT_NOT_FOUND',
  APPT_QR_MISMATCH: 'APPT_QR_MISMATCH',
  APPT_QR_ALREADY_USED: 'APPT_QR_ALREADY_USED',
  APPT_TOO_EARLY: 'APPT_TOO_EARLY',
  APPT_TOO_LATE: 'APPT_TOO_LATE',
  APPT_COACH_NOT_ASSIGNED: 'APPT_COACH_NOT_ASSIGNED',
  APPT_WAITING_CLIENTS: 'APPT_WAITING_CLIENTS',
  APPT_ALREADY_STARTED: 'APPT_ALREADY_STARTED',
  APPT_INTERNAL_ERROR: 'APPT_INTERNAL_ERROR',
  APPT_NO_CLIENT_PARTICIPANTS: 'APPT_NO_CLIENT_PARTICIPANTS', // Nouveau: anomalie aucun client trouvé alors qu'on s'y attend
} as const;
export type ScanQrErrorCode = typeof SCAN_QR_ERROR_CODES[keyof typeof SCAN_QR_ERROR_CODES];

export const SCAN_PARTICIPANT_ERROR_CODES = {
  PARTICIPANT_QR_INVALID: 'PARTICIPANT_QR_INVALID',
  PARTICIPANT_QR_EXPIRED: 'PARTICIPANT_QR_EXPIRED',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  PARTICIPANT_APPT_MISMATCH: 'PARTICIPANT_APPT_MISMATCH',
  PARTICIPANT_NOT_CLIENT: 'PARTICIPANT_NOT_CLIENT',
  COACH_NOT_ASSIGNED: 'COACH_NOT_ASSIGNED',
  PARTICIPANT_ALREADY_PRESENT: 'PARTICIPANT_ALREADY_PRESENT',
  PARTICIPANT_INTERNAL_ERROR: 'PARTICIPANT_INTERNAL_ERROR',
} as const;
export type ScanParticipantErrorCode = typeof SCAN_PARTICIPANT_ERROR_CODES[keyof typeof SCAN_PARTICIPANT_ERROR_CODES];

// (Option) mapping générique futur des messages UI
// export const ERROR_MESSAGES_FR: Record<string,string> = { ... };
